config/routes.rb
Crowdfunder::Application.routes.draw do

  resources :projects do
    resources :pledges, only: :create
    resources :tiers
  end

  resources :users

   resources :projects do

   end

end

  #   end

app/models/pledge.rb
class Pledge < ActiveRecord::Base

  belongs_to :project
  belongs_to :tier
  belongs_to :backer, class_name: "User"

end

app/models/project.rb
class Project < ActiveRecord::Base

  # has_many :users
  has_many :pledges
  has_many :tiers

  belongs_to :owner, class_name: "User"
  accepts_nested_attributes_for :tiers

end

app/models/tier.rb
class Tier < ActiveRecord::Base
  belongs_to :project

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  has_many :projects
  has_many :pledges
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_user=(user)
    if user.nil?
      session.delete(:user_id)
    else
      session[:user_id] = user.id
    end
  end

  helper_method :current_user

end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController

end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
  def index
    @projects = Projects.all
  end

  def show
    @project = Projects.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def edit
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to projects_url
    else
      render :new
    end
  end

  def update
    @project = Project.find(params[:id])

    if @project.update_attributes(project_params)
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to project_path
  end

  private
  def project_params
    params.require(:project).permit (:name, :description, :start_time, :end_time, :goal_in_dollars, :owner_id, :created_at, :updated_at)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
    @tier = Tier.where("project_id = ?","#{params[:id]}").all
  end

  def new
    @project = Project.new
  end

  def edit
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to projects_path
    else
      render :new
    end
  end

  def update
    @project = Project.find(params[:id])

    if @project.update_attributes(project_params)
      redirect_to project_path(@project)
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to project_path
  end

  private
    def project_params
      params.require(:project).permit(:name, :description, :start_date, :end_date, :goal_in_dollars, :owner_id, :project_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    session[:redirect_after_login] = request.referrer
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to session[:redirect_after_login], :notice => "Logged in"
    else
      flash.now[:alert] = "Invalid e-mail or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to project_path
  end

end

app/controllers/tier_controller.rb
class TierController < ApplicationController

  def index
    @tiers = Tiers.all
  end

  def show
    @tiers = Tiers.find(params[:id])
  end

  def new
    @tier = Tier.new
  end

  def edit
    @Tier = Tier.find(params[:id])
  end

  def create
    @Tier = Tier.new(project_params)

    if @tier.save
      redirect_to tiers_url
    else
      render :new
    end
  end

  def update
    @tier = Tier.find(params[:id])

    if @tier.update_attributes(tier_params)
      redirect_to tier_path(@tier)
    else
      render :edit
    end
  end

  def destroy
    @tier = Tier.find(params[:id])
    @tier.destroy
    redirect_to tier_path
  end

  private
  def tier_params
    params.require(:tier).permit (:name, :description, :price_in_dollars, :project_id, :created_at, :updated_at)
  end

end

app/controllers/tiers_controller.rb
class TiersController < ApplicationController
  before_filter :load_project

  def index
    @tiers = Tier.all
  end

  def show
    @tier = Tier.find(params[:id])
  end

  def new
    # @project = Project.find(params[:project_id])
    @tier = Tier.new
  end

  def edit
    @tier = Tier.find(params[:id])
  end

  def create
    # project = Project.find( params[:project_id] )
    # project.tiers.build( tier_params )

    @tier = Tier.new(tier_params)
    @tier.project_id = params[:project_id]

    if @tier.save
      redirect_to @project
    else
      render :new
    end
  end

  def update
    @tier = Tier.find(params[:id])

    if @tier.update_attributes(tier_params)
      redirect_to tier_path(@tier)
    else
      render :edit
    end
  end

  def destroy
    @tier = Tier.find(params[:id])
    @tier.destroy
    redirect_to tier_path
  end

  private
  def tier_params
    params.require(:tier).permit(:name, :description, :price_in_dollars, :created_at, :updated_at)
  end

  def load_project
    @project = Project.find(params[:project_id])
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def index
    @users = Users.all
  end

  def show
    @user = Users.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @User = User.find(params[:id])
  end

  def create
    @user = User.new(project_params)

    if @user.save
      redirect_to users_url
    else
      render :new
    end
  end

  def update
    @user = Users.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = Users.find(params[:id])
    @user.destroy
    redirect_to user_path
  end

  private
  def user_params
    params.require(:user).permit (:email, :crypted_password, :salt, :created_at, :updated_at)
  end

end




end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @User = User.find(params[:id])
  end

  def create
    debugger
    @user = User.new(user_params)

    if @user.save
      redirect_to projects_url
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to user_path
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/pledge_helper.rb
module PledgeHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tier_helper.rb
module TierHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdfunder</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<% f.inputs do %>
  <%= f.input :name %>
  <%= f.input :description %>
  <h3>Tiers</h3>
  <div id='tiers'>
    <%= f.semantic_fields_for :tiers do |tier| %>
      <%= render 'project_fields', :f => task %>
    <div class='links'>
      <%= link_to_add_association 'add task', f, :tasks %>
    </div>
  <% end %>
  <% f.buttons do %>
    <%= f.submit 'Save' %>
  <% end %>
<% end %>

app/views/projects/_project_fields.html.erb
<!--
<div id="tier">
  <%= f.simple_fields_for :tiers do |tier| %>
    <%= render 'tier_fields', :f => task %>

  <div class='links'>
    <%= link_to_add_association 'add task', f, :tiers %>
  </div>
</div>



 -->

app/views/projects/edit.html.erb
<h1>Project#edit</h1>
<p>Find me in app/views/project/edit.html.erb</p>

<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this product from being saved:</h2>

     <ul>
     <% @project.errors.full_messages.each do  |msg| %>
      <li><%= msg %></li>
     <% end %>
     </ul>
  </div>
<% end %>

<div class="field">
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :description %><br/>
  <%= f.text_field :description %><br/>
</div>
<div class="field">
  <%= f.label :goal_in_dollars %><br/>
  <%= f.number_field :goal_in_dollars %><br/>
</div>
<div class="field">
  <%= f.label :start_date %><br/>
  <%= f.date_field :start_date %><br/>
</div>
<div class="field">
  <%= f.label :end_date %><br/>
  <%= f.date_field :end_date %><br/>
</div>

<!-- <ul>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
</ul>
 -->
<div class="Submit">
  <%= f.submit %>
</div>

<%= link_to 'Show', project_path(@project) %>
<%= link_to 'Back', projects_path %>
<% end %>

app/views/projects/index.html.erb
<h1>Projects! These are the projects!</h1>

<ul>
  <% @projects.each do  |project| %>
  <%= link_to project_path(project.id) do %>
  <h2>
      <%= project.name %>
      <%= project.goal_in_dollars %>

  </h2>
  <% end %>

<% end %>

</ul>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= form_for(@project) do |f| %>
<% if @project.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
    <ul>
    <% @project.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

    <div class="field">
      <%= f.label :name %><br/>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :description %><br/>
      <%= f.text_field :description %>
    </div>
    <div class="field">
      <%= f.label :start_date %><br/>
      <%= f.date_field :start_date %>
    </div>
    <div class="field">
      <%= f.label :end_date %><br/>
      <%= f.date_field :end_date %>
    </div>
    <div class="field">
      <%= f.label :goal_in_dollars %><br/>
      <%= f.number_field :goal_in_dollars %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/projects/show.html.erb
<h1>Project</h1>
<p>
  <b>Name:</b>
  <%=@project.name %>
</p>

<p>
  <b>Description:</b>
  <%= @project.description %>
</p>

<p>
  <b>Price:</b>
  <%= @project.goal_in_dollars  %>
</p>

<p>
  <b>Start Date:</b>
  <%= @project.start_date %>
</p>

<p>
  <b>End Date:</b>
  <%= @project.end_date %>
</p>

<p>
  <b>Owner Name</b>
  <%= @project.owner_id %>
</p>


<h2>Tiers</h2>
<% @tier.each do |tier| %>
  <p>
    <b>Tier Name:</b>
    <%= tier.name %>
  </p>
  <p>
    <b>Tier Descrption:</b>
    <%= tier.description %>
  </p>
  <p>
    <b>Price in Dollars</b>
    <%= tier.price_in_dollars %>
  </p>
<% end %>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %> |
<%= link_to 'Add Tiers', new_project_tier_path(@project) %>

app/views/tiers/new.html.erb
<h1>Add a Tier</h1>

<%= form_for([@project,@tier]) do |f| %>
<% if @tier.errors.any? %>
  <div id="error_explaination">
    <h2><%= pluralize(@tier.errors.count, "error") %> Prohibited this tier from being saved:</h2>
    <ul>
    <% @tier.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br/>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price_in_dollars %>
    <%= f.text_field :price_in_dollars %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any?   %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
          <% end %>
          </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :email %><br/>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :password %><br/>
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br/>
      <%= f.password_field :password_confirmation %>
    </div>

    <div class="actions"><%= f.submit %></div>

  <% end %>